my_backend_app:
          image: nginx:latest
          ports:
            - 80
postgres:
          image: postgres
          container_name: postgres
          ports:
            - 5432
          volumes:
            - ./test/scripts/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
          environment:
            - POSTGRES_DB=reference-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
zookeeper:
          image: "docker.io/bitnami/zookeeper:3"
          container_name: zookeeper
          ports:
            - 2181
          environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
