version: '3'
services:
  postgres:
    image: docker.io/postgres
    container_name: postgres
    ports:
      - 5432
    volumes:
      - >-
        ./test/scripts/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_DB=reference-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3'
    container_name: zookeeper
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    container_name: kafka
    ports:
      - 9092
      - 9093
    environment:
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181'
      - ALLOW_PLAINTEXT_LISTENER=yes
      - >-
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - 'KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093'
      - >-
        KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    links:
      - zookeeper
  reference-domain-service:
    container_name: reference-domain-service
    image: 'nginx:latest'
    volumes:
      - './test/secrets/secrets.properties:/data/secrets.properties'
    ports:
      - 9102
    environment:
      - 'SPRING_CLOUD_STREAM_KAFKA_BINDER_ERS=kafka:9092'
      - SPRING_DATA_MONGODB_HOST=mongodb
      - 'SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS=kafka:9092'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reference-db'
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOCREATETOPICS=true
      - SPRING_DATA_MONGODB_DATABASE=locations_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=my-user
      - SPRING_DATA_MONGODB_PASSWORD=my-password
      - SECRETSVOL=/data/
    links:
      - kafka
  newman_component_test:
    image: iflavoursbv/newman-alpine
    command: bash -c "pwd && ls -lrt"
    links: 
      - reference-domain-service
